name: Generate docs from pod

on:
  push:
    branches:
      - main

jobs:
  generate-doc:
    uses: Omochice/tataku-share-actions/.github/workflows/generate-doc.yml@96f5d737c27993252f4f7ca0ea290bb1a6aec1ff # v2.0.13
    permissions:
      contents: write
      pull-requests: write
    secrets:
      APP_ID: ${{ secrets.PODENO_APP_ID }}
      PRIVATE_KEY: ${{ secrets.PODENO_PRIVATE_KEY }}
